fix(readme): refer to own repos file
tier4/CalibrationTools pull request #7
Opened 2022-07-07 08:22 UTC by aohsato

## Description

I changed to manage repos file in`calibration_tools` to build itself in parallel with autoware setup.

## Related links

Please refer to [Installation procedures](https://github.com/tier4/CalibrationTools/tree/fix/readme_repos#installation-procedures) in this PR.

## Notes for reviewers

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2022-07-07 09:06 UTC, yabuta requested changes

2022-07-07 09:06 UTC, yabuta commented on calibration_tools.repos
> +    url: git@github.com:tier4/calibration_tools.git
This URL is wrong.
git@github.com:tier4/CalibrationTools.git

2022-07-10 23:55 UTC, yabuta approved these changes
LGTM

2022-07-11 00:34 UTC, knzo25 approved these changes
LGTM

2022-07-11 01:31 UTC, merged